name: kokoro-cuda

services:
  kokoro:
    build: .
    ports:
      - "8880:8880"
    environment:
      - MODEL_DIR=/app/models
      - VOICES_DIR=/app/voices
    volumes:
      - models:/app/models
      - voices:/app/voices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  models:
  voices:
